/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.fp7.gradle;

import io.github.fp7.maven_gradle.Test;

public class Library {

    public static void main(String[] args) {
        String foo = io.github.fp7.maven_gradle.Test.foo();
    }
}
